const dogsData = [
    {
        id: 1,
        name: 'Buddy',
        breed: 'Golden Retriever',
        ageMonths: 12,
        gender: 'Male',
        price: 800,
        image: 'https://takehome.statledger.io/api/images/dog1.jpg',
    },
    {
        id: 2,
        name: 'Luna',
        breed: 'German Shepherd',
        ageMonths: 9,
        gender: 'Female',
        price: 900,
        image: 'https://takehome.statledger.io/api/images/dog2.jpg',
    },
    {
        id: 3,
        name: 'Max',
        breed: 'Labrador Retriever',
        ageMonths: 15,
        gender: 'Male',
        price: 750,
        image: 'https://takehome.statledger.io/api/images/dog3.jpg',
    },
    {
        id: 4,
        name: 'Daisy',
        breed: 'Beagle',
        ageMonths: 7,
        gender: 'Female',
        price: 600,
        image: 'https://takehome.statledger.io/api/images/dog4.jpg',
    },
    {
        id: 5,
        name: 'Rocky',
        breed: 'Boxer',
        ageMonths: 10,
        gender: 'Male',
        price: 850,
        image: 'https://takehome.statledger.io/api/images/dog5.jpg',
    },
    {
        id: 6,
        name: 'Buddy',
        breed: 'Golden Retriever',
        ageMonths: 10,
        gender: 'Male',
        price: 800,
        image: 'https://takehome.statledger.io/api/images/dog6.jpg',
    },
    {
        id: 7,
        name: 'Lola',
        breed: 'French Bulldog',
        ageMonths: 8,
        gender: 'Female',
        price: 650,
        image: 'https://takehome.statledger.io/api/images/dog7.jpg',
    },
    {
        id: 8,
        name: 'Max',
        breed: 'German Shepherd',
        ageMonths: 14,
        gender: 'Male',
        price: 950,
        image: 'https://takehome.statledger.io/api/images/dog8.jpg',
    },
];

const catsData = [
    {
        id: 9,
        name: 'Whiskers',
        breed: 'Siamese',
        ageMonths: 8,
        gender: 'Male',
        price: 600,
        image: 'https://takehome.statledger.io/api/images/cat1.jpg',
    },
    {
        id: 10,
        name: 'Luna',
        breed: 'Persian',
        ageMonths: 12,
        gender: 'Female',
        price: 750,
        image: 'https://takehome.statledger.io/api/images/cat2.jpg',
    },
    {
        id: 11,
        name: 'Simba',
        breed: 'Maine Coon',
        ageMonths: 10,
        gender: 'Male',
        price: 700,
        image: 'https://takehome.statledger.io/api/images/cat3.jpg',
    },
    {
        id: 12,
        name: 'Mittens',
        breed: 'Ragdoll',
        ageMonths: 7,
        gender: 'Female',
        price: 650,
        image: 'https://takehome.statledger.io/api/images/cat4.jpg',
    },
    {
        id: 13,
        name: 'Leo',
        breed: 'Bengal',
        ageMonths: 14,
        gender: 'Male',
        price: 800,
        image: 'https://takehome.statledger.io/api/images/cat5.jpg',
    },
    {
        id: 14,
        name: 'Oreo',
        breed: 'Domestic Shorthair',
        ageMonths: 5,
        gender: 'Female',
        price: 550,
        image: 'https://takehome.statledger.io/api/images/cat6.jpg',
    }
];

module.exports = { catsData, dogsData }
