services:
  takehome:
    build: "."
    image: "takehome_api"
    container_name: "takehome_api"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.takehome.entrypoints=websecure"
      - "traefik.http.routers.takehome.rule=Host(`takehome.statledger.io`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.takehome.tls=true"
      - "traefik.http.routers.takehome.tls.certresolver=lets-encrypt"

networks:
  default:
    name: proxy
    external: true
